// <auto-generated />
using System;
using AjoOWithEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AjoOWithEF.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211026223958_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AjoOWithEF.Data.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<double>("Contribution")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("LoanRepayment")
                        .HasColumnType("float");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 20000.0,
                            Contribution = 20000.0,
                            Date = new DateTime(2015, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanRepayment = 0.0,
                            MemberId = 3
                        },
                        new
                        {
                            Id = 234002,
                            Balance = 30000.0,
                            Contribution = 30000.0,
                            Date = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanRepayment = 0.0,
                            MemberId = 1
                        },
                        new
                        {
                            Id = 234003,
                            Balance = 40000.0,
                            Contribution = 40000.0,
                            Date = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanRepayment = 0.0,
                            MemberId = 2
                        });
                });

            modelBuilder.Entity("AjoOWithEF.Data.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gurantor1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gurantor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LoanAmount")
                        .HasColumnType("float");

                    b.Property<double>("LoanRate")
                        .HasColumnType("float");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<double>("MonthsOfRepayment")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 33001,
                            ApprovedBy = "Adewunmi Idris",
                            Date = new DateTime(2015, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gurantor1 = "Chief Babatunde Ogwu",
                            Gurantor2 = "Chief Mrs. Ronke Great",
                            LoanAmount = 2000000.0,
                            LoanRate = 7.5,
                            MemberId = 2,
                            MonthsOfRepayment = 24.0
                        },
                        new
                        {
                            Id = 33002,
                            ApprovedBy = "Adewunmi Idris",
                            Date = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gurantor1 = "Chief Sunday Agbro",
                            Gurantor2 = "Mrs. Sikiratu Sindodo",
                            LoanAmount = 1000000.0,
                            LoanRate = 7.5,
                            MemberId = 1,
                            MonthsOfRepayment = 24.0
                        },
                        new
                        {
                            Id = 33003,
                            ApprovedBy = "Adewunmi Idris",
                            Date = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gurantor1 = "Mr. Sunday Yusuf",
                            Gurantor2 = "Mr. Adefula Agbanikoko",
                            LoanAmount = 3000000.0,
                            LoanRate = 8.5,
                            MemberId = 3,
                            MonthsOfRepayment = 30.0
                        });
                });

            modelBuilder.Entity("AjoOWithEF.Data.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Addo round about, Ajah",
                            ContactNo = "08108511957",
                            Department = "IT",
                            Email = "wynny123@gmail.com",
                            FirstName = "Edwin",
                            Surname = "Ehiabhilyson"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Addo round about, Ajah",
                            ContactNo = "08108511957",
                            Department = "IT",
                            Email = "apprill2221@gmail.com",
                            FirstName = "April",
                            Surname = "Edwin"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Addo round about, Ajah",
                            ContactNo = "08108511957",
                            Department = "Education",
                            Email = "moyo@gmail.com",
                            FirstName = "Moyo",
                            Surname = "Edwin"
                        });
                });

            modelBuilder.Entity("AjoOWithEF.Data.Account", b =>
                {
                    b.HasOne("AjoOWithEF.Data.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AjoOWithEF.Data.Loan", b =>
                {
                    b.HasOne("AjoOWithEF.Data.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
